<a href="https://colab.research.google.com/github/rybakinaea/DZ-MLP/blob/main/%D0%9F%D0%A0_1_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическая работа 1-1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy
numpy.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
import numpy as np
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [ ]:
import numpy as np
vector = np.ones(7) * 7
np.resize(vector, 7)

array([7., 7., 7., 7., 7., 7., 7.])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
import numpy as np
vector = np.arange(10, 101, 2)
vector

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
vector = np.random.randint(100, size=(10,))
print (vector)
vector_reversed = vector[::-1]
print (vector_reversed)

[41 42 97 25 30 86 29  3  0 51]
[51  0  3 29 86 30 25 97 42 41]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
matrix = np.zeros((3, 3))
for i in range(3):
  for j in range(3):
    matrix[i, j] = i * 3 + j
print

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [5]:
import numpy as np
def create_matrix():
  return np.ones((4, 4)) - np.eye(4)
result = create_matrix()
print (result)

[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
import numpy as np
diag_matrix = np.diag(np.arange(1, 5))
diag_matrix[~np.eye(4, dtype=bool)] = 7
print(diag_matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
import numpy as np
matrix = np.zeros((5, 5))
for i in range(5):
    matrix[i] = np.arange(0, 5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [19]:
import numpy as np
matrix = np.random.randint(10,size = (10, 10))
matrix

array([[6, 8, 9, 4, 4, 0, 9, 8, 9, 0],
       [5, 5, 2, 0, 1, 4, 9, 9, 3, 3],
       [5, 8, 4, 7, 9, 6, 6, 4, 6, 5],
       [7, 6, 3, 9, 8, 6, 5, 7, 6, 2],
       [5, 7, 4, 8, 9, 0, 9, 5, 8, 2],
       [2, 8, 2, 1, 1, 4, 9, 6, 9, 9],
       [0, 6, 6, 2, 2, 0, 8, 3, 8, 5],
       [1, 3, 4, 2, 8, 8, 4, 7, 6, 9],
       [7, 8, 7, 2, 8, 8, 9, 3, 4, 5],
       [7, 0, 9, 9, 8, 4, 8, 4, 0, 8]])

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [20]:
matrix= np.random.randint(10,size = (10, 10))
matrix

array([[8, 3, 5, 1, 8, 1, 5, 3, 4, 8],
       [2, 3, 9, 2, 4, 8, 8, 7, 4, 1],
       [8, 8, 5, 0, 4, 5, 2, 4, 3, 0],
       [6, 3, 6, 8, 9, 1, 3, 1, 3, 6],
       [4, 6, 8, 7, 9, 5, 2, 5, 4, 4],
       [0, 0, 7, 9, 2, 6, 4, 1, 0, 1],
       [1, 4, 1, 7, 0, 8, 5, 1, 6, 7],
       [5, 5, 2, 2, 7, 2, 2, 5, 6, 8],
       [6, 7, 1, 9, 6, 7, 5, 8, 5, 0],
       [4, 2, 6, 5, 4, 0, 9, 0, 1, 0]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [21]:
matrix = np.random.randint(10,size = (10, 10))
matrix.max(axis =1,keepdims=True)
matrix.min(axis =1,keepdims=True)
np.concatenate((matrix,matrix.max(axis =1,keepdims=True),matrix.min(axis =1,keepdims=True)),axis = 1)

array([[2, 4, 8, 9, 9, 0, 4, 8, 1, 7, 9, 0],
       [4, 7, 6, 1, 1, 7, 8, 1, 1, 0, 8, 0],
       [5, 8, 1, 7, 7, 0, 7, 4, 8, 7, 8, 0],
       [3, 7, 7, 4, 0, 6, 3, 5, 5, 3, 7, 0],
       [5, 5, 3, 6, 7, 2, 6, 2, 7, 0, 7, 0],
       [3, 0, 4, 4, 1, 6, 2, 9, 6, 6, 9, 0],
       [2, 4, 9, 6, 0, 8, 0, 1, 9, 7, 9, 0],
       [4, 2, 6, 2, 1, 0, 9, 6, 5, 9, 9, 0],
       [6, 5, 7, 7, 6, 3, 6, 3, 9, 3, 9, 3],
       [4, 1, 5, 7, 4, 1, 6, 3, 6, 4, 7, 1]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [22]:
a =np.mat(np.arange(1,50)[1::2]).reshape(4,6)
b =np.mat(np.arange(1,50)[2::2]).reshape(6,4)
print(a*b)
print(np.linalg.inv(a*b))

[[1246 1330 1414 1498]
 [2902 3130 3358 3586]
 [4558 4930 5302 5674]
 [6214 6730 7246 7762]]
[[-3.66503876e+11  3.21853878e-04  1.09951163e+12 -7.33007752e+11]
 [-7.33007752e+11  2.19902326e+12 -2.19902326e+12  7.33007752e+11]
 [ 2.56552713e+12 -4.39804651e+12  1.09951163e+12  7.33007752e+11]
 [-1.46601550e+12  2.19902326e+12  0.00000000e+00 -7.33007752e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [23]:
matrix = np.zeros((8,8), dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])