<a href="https://colab.research.google.com/github/rybakinaea/DZ-MLP/blob/main/%D0%9F%D0%A0_1_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическая работа 1-1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy
numpy.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [2]:
import numpy as np
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [3]:
import numpy as np
vector = np.ones(7) * 7
np.resize(vector, 7)

array([7., 7., 7., 7., 7., 7., 7.])

4) Создать вектор заполненный четными числами от 10 до 100

In [9]:
import numpy as np
vector = np.arange(10, 101, 2)
vector

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [15]:
vector = np.random.randint(100, size=(10,))
print (vector)
vector_reversed = vector[::-1]
print (vector_reversed)

[41 42 97 25 30 86 29  3  0 51]
[51  0  3 29 86 30 25 97 42 41]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [18]:
matrix = np.zeros((3, 3))
for i in range(3):
  for j in range(3):
    matrix[i, j] = i * 3 + j
print

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.